default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    UI.important "Testing fastlane command"
  end

  desc "Install cocoa-pods"
  lane :prepare_app do
    UI.important "Installing cocoa-pods..."
    #cocoapods(repo_update: true, clean_install: true)
    sh("pod", "install")
  end

  desc "Test the app"
    lane :test_app do
    UI.important "Testing the app"
    xcversion(version: "15.2")
    scan()
  end

  desc "Build the app"
    lane :build_sample_app do
    UI.important "Building the app..."
    xcversion(version: "15.2")
    gym(export_method: "development")
  end


end
